heat_template_version: 2014-10-16

description: >
  A template which provides a creates a loadbalancer using neutron's LBaaS.

parameters:

  # What version of OpenShift Enterprise to install
  # This value is used to select the RPM repo for the OSE release to install
  ose_version:
    type: string
    description: >
      The version of OpenShift Enterprise to deploy

  key_name:
    description: >
      A pre-submitted SSH key to access the VM hosts
    type: string
    constraints:
    - custom_constraint: nova.keypair

  image:
    type: string
    default: ''

  flavor:
    description: >
      Define the hardware characteristics for the VMs: CPU, Memory, base disk
    type: string
    constraints:
    - custom_constraint: nova.flavor

  hostname:
    description: >
      The load balancer hostname portion of the FQDN
    type: string
    constraints:
    - allowed_pattern: '[a-z0-9\-]*'
      description: Hostname must contain only characters [a-z0-9\-].

  domain_name:
    description: >
      All VMs will be placed in this domain
    type: string

  rhn_username:
    description: >
      A valid user with entitlements to RHEL and OpenShift software repos
    type: string

  rhn_password:
    description: >
      The password for the RHN user
    type: string
    hidden: true

  # Red Hat satellite subscription parameters
  sat6_hostname:
    type: string
    description: >
      The hostname of the Satellite 6 server which will provide software updates
    default: ''

  sat6_organization:
    type: string
    description: >
      An organization string provided by Sat6 to group subscriptions
    default: ''

  sat6_activationkey:
    type: string
    description: >
      An activation key string provided by Sat6 to enable subscriptions

  rhn_pool:
    description: >
      A subscription pool containing the RHEL and OpenShift software repos
      OPTIONAL
    type: string
    hidden: true

  extra_rhn_pools:
    type: comma_delimited_list
    description: List of rhn pools which will be installed on each node.
    default: ''

  dns_ip:
    description: IP address of the DNS server
    type: string

  ssh_user:
    description: >
      The user for SSH access to the VM hosts
    type: string

  ansible_public_key:
    description: >
      The SSH public key that Ansible will use to access master and node hosts
      This will be placed on each VM host in /root/.ssh/authorized_keys
    type: string

  fixed_subnet:
    description: >
      The name or ID of the internal IPv4 space
    type: string
    constraints:
    - custom_constraint: neutron.subnet

  single_lb_member_address:
    type: string

  master_hostname:
    type: string

  floatingip_ip:
    type: string

  fixed_network:
    description: >
      The name or ID of the internal network
    type: string
    constraints:
    - custom_constraint: neutron.network

  floating_subnet:
    description: >
      The name or ID of the external subnet
    type: string
    constraints:
    - custom_constraint: neutron.subnet

  fixed_subnet:
    description: >
      The name or ID of the internal IPv4 space
    type: string
    constraints:
    - custom_constraint: neutron.subnet

  extra_repository_urls:
    type: comma_delimited_list
    description: List of repository URLs which will be installed on each node.
    default: ''

  extra_docker_repository_urls:
    type: comma_delimited_list
    description: List of docker repository URLs which will be installed on each node, if a repo is insecure use '#insecure' suffix.
    default: ''

  stack_name:
    type: string
    default: ''

  bastion_node:
    type: string
    description: >
      The name or ID of the bastion instance.
    default: ''

  skip_dns:
    type: boolean

resources:
  lb:
    type: OS::Neutron::LBaaS::LoadBalancer
    properties:
        name: master_node_balancer
        vip_address: {get_param: floatingip_ip}
        vip_subnet: {get_param: floating_subnet}

  listener:
    type: OS::Neutron::LBaaS::Listener
    properties:
      loadbalancer: {get_resource: lb}
      name: listener_8443
      protocol: TCP
      protocol_port: 8443

  lb_pool:
    type: OS::Neutron::LBaaS::Pool
    properties:
      listener: {get_resource: listener}
      name: lb_pool_of_masters
      description: Load balancer for OpenShift hosts.
      lb_algorithm: ROUND_ROBIN
      protocol: HTTPS
      session_persistence:
        type: SOURCE_IP
 
#  rules:
#    repeat:
#      for_each:
#        <%ip_address%>: {get_param: members}
#      template:
#        poolmembers:
#          type: OS::Neutron::LBaaS::PoolMember
#          properties:
#            pool: {get_resource: lb_pool}
#            protocol_port: 8443
#            address: <%ip_address%>

  poolmembers:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      pool: {get_resource: lb_pool}
      protocol_port: 8443
      address: {get_param: single_lb_member_address}
#      address: 192.168.0.4

  lb_monitor:
    type: OS::Neutron::LBaaS::HealthMonitor
    properties:
      pool: { get_resource: lb_pool }
      type: TCP
      delay: 15
      max_retries: 5
      timeout: 10

outputs:
  console_url:
    description: URL of the OpenShift web console
    value:
      str_replace:
        template: "https://%hostname%.%domainname%:8443/console/"
        params:
          '%hostname%': {get_param: hostname}
          '%domainname%': {get_param: domain_name}

  api_url:
    description: URL entrypoint to the OpenShift API
    value:
      str_replace:
        template: "https://%hostname%.%domainname%:8443/"
        params:
          '%hostname%': {get_param: hostname}
          '%domainname%': {get_param: domain_name}
